#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := medlo-node

EXCLUDE_COMPONENTS := aws_iot http_server bt coap libsodium paho.mqtt.embedded-c

include $(IDF_PATH)/make/project.mk

